name: Build caddy-linux-amd64
on:
  push:
    paths:
        - 'caddy-linux-amd64.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@master
    
    - name: install xcaddy
      run: |
        tag_name=`curl -s https://api.github.com/repos/caddyserver/xcaddy/releases | grep 'tag_name' | sed -n '1p' | cut -d\" -f4`
        wget -O ./xcaddy https://github.com/caddyserver/xcaddy/releases/download/${tag_name}/xcaddy_${tag_name}_linux_amd64
        chmod 777 ./xcaddy

    - name: build caddy
      run: |
        export GOARCH=amd64
        export GOOS=linux
        ./xcaddy build \
          --with github.com/mholt/caddy-webdav

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy
